package vandy.mooc.assignments.framework.downloader;

import android.support.annotation.Nullable;

/**
 * Generic resource decoder interface that decodes from an input data type to an
 * output resource type.
 *
 * @param <R> The output resource type generated by the encoding process.
 */
public interface Decoder<R> {
    /**
     * Called by the framework to determine if the decoder can or needs to pre
     * validate incoming content by calling the isContentValid() method.
     *
     * @return {@code true} if canValidateContent should be called, {@code
     * false} if not.
     * @param source An input source data type.
     */
    boolean canValidateContent(Class source);

    /**
     * Returns whether or not the decoder implementation can read and convert
     * from the specified input source.
     *
     * @param source An input class type.
     * @return {@code true} if the decoder can process input from the specified
     * data type.
     */
    boolean canDecodeFrom(Class source);

    /**
     * Examines the input stream to determine if the stream contains data that
     * can be decoded into the by this resource type.
     *
     * @param input An input data source.
     * @return {@code true} input data source contains valid data that can be
     * decoded by this decoder.
     */
    boolean isContentValid(Object input);

    /**
     * Decodes a data object from the passed input stream (not currently used
     * due to rewind issues).
     *
     * @param input An input data source.
     * @return An instance of the decoded data resource.
     */
    @Nullable
    R decode(Object input, int width, int height);
}
